{% set name = "records" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47e4874096f4a8f4b5bcad8c7c7cf512be36186e6e263ff3dfd750b05ff0d3c4

build:
  noarch: python
  entry_points:
    - records = records:cli
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - sqlalchemy
    - tablib
    - docopt
    - pandas

test:
  imports:
    - records

  commands:
    - records --help
    - pip check
    
  requires: 
    - pip

about:
  home: https://github.com/kennethreitz/records
  license_file: LICENSE
  license: ISC
  license_family: OTHER
  summary: 'SQL for Humans'
  dev_url: https://github.com/kennethreitz/records

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
