travis:
  secure:
    BINSTAR_TOKEN: VyJd2bjQrjvG2Jh5b5onIXSeL0zUTFmxvWU6Dk28Wc+foPcDxvqMhrq/VVnhq+BbteDm6bQiU9yzoor3fMRIIOwg0tKa+yRdlDMxUrUz1aKXLZYSre+hF8qfFzEqUXJA/ZbuCbyz2xWUTHVu6s2vMa6SDLag+wHF8sTv+AUGsKVEYWlg0x1Oqzn5GVRmk8Lo7R6QnQ/aPUAM2fcBh/y5xeTZeL8dzELEIMWuuEJkVkrYXyI3vNkdkhwn8CAm7yqAhafbzc4+oHglQglKw4DhN82xo5hhD3Lu1lK7iW1ykUeFRZBHZyxvCoPBvclND8Ugnu2OqwvKq7D3wWwjOxmEnseEtBLuDF7B2DH+fK0iidmBannwh/CkrGyiChFBYxULqJMRqBh/7P62pdhAYCVNlzNrRRolpWhjkwvcv+BtCYI0t8jRVsCqZFy5lDnNbPR1tPI44K6qkDbkpvf4tmW0yeVcd5dfY5qJQsqaTaugzzpbdke1bhAJqgr6WVGgEfpDLSwj+lBV9M0e2sUzqqwn+YqPbwZvrUM1iiS4An99UDF15KdlYFORJzDan2v/NdBD9NmvjcML7AjcyQCu1YYf+ytphIbywFFdDOXvl9VDyLIv1iIkGf00UN1SXHP8HMrhs7lqT+rzhRmXcuNp+XEEOour+4NSST6mb8e3dpEnyRs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
