travis:
  secure:
    BINSTAR_TOKEN: p7LE21UnoxHVe7+FMGHGZCyua8MPyso41mys2hflYvbhVdTGBsa9NTlekF6yKf1N3ekTSPyuLylZ/YEDnRTWtl9J0r083g6PQTFQdVs/gZE8AHHJgie6F3dHl6GHPv2rz4o4t33ZQSMk6sk7VcoDSH0Kqsj+kq6YdR27yp0mbEr6xAgE4iilMJdHCKE0HyZEHSYKtnoqJh7tq3r55OcVRUU3K+sp8dQquKNX5mq3otqLkQLoa+oB2NgvaJ49w2x7CIyiTO/2z7nhRf5DO0vJVibh7HufRWGVznHfPeFBmj2pIEetRSfwiv9DY8jhoX4FXSVUgag4ptujIwoAOO2enPE4DWuT16LREo1EOvyaSOoiGRWNxl/dxIcCUCCA9zL24E9fE/8Q6Ab5qCy6O/hSj/7X6ox9bncqNPi7yPczeJMxOZGeLsTUYQ8vnVby0n0qE4Z9gZB86TrYMKZg7nfmoNaywhRdlGln8RiUGf/2D64UiTJRiDV87qRYu2m2xyEKpLRd12W1fIRnyc4ICkebmQ3jUOF3J/FLIdwxl/fj7ojS8ETBKuVJUlzkkoFV3k37uG11sJCMaP0AZy/k4pCu2sGO+MR5qMAk/tsHGd8BbAJykxzRPY8gdOjkVK4sKN0yntvDGKnsS7yqbFwbRWFhAzpM0wfGvsdWRxtOciOVnkw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
