travis:
  secure:
    BINSTAR_TOKEN: wyHAtCpv+UEUx/S/OtizXsOti3gMbyzn+bcbdJUiFDGvzdi0fHrqITiPyqweHrpwVJoBnG8zOsxG/IaVz51BfaO0spPinp9qwbSqGdKr3EKI9LwBGblnTV4c7ooAMesUwYDME0f2VwwSEhGS4zQ7KmFKaTeK2TOqn/4hAQh5bhUKwF6pERRDebJ739XudwhJzvk8evKatZ0D5Zn3wYwhDgwPJRE4pls+N7utMCPaVgblsrw2nzc0TAa6VG5zijTPLWV1O5mCGE/7Q9r2v643LBo8RcTmFNHzMLKYiYpc6NXWH7k2QiLoOK5jgzy61aqeujWOz2x/qbtFnrQ7967hdnxCtKvw5fDZyNL9T7s7VBA9yfoEzCzTwAs/i/fmugG1oGg9cchw65qNMAFyTzZjxQWMLhOBzB+/U2QYuCEJkac3wQsKzyORCLCFiJZw4ygscX4ISCOq64ZYJAVRVxikWJRrziryRG7aP7QPgh2F5s7jDNYxFBdrk9W3f7rJcNnq7oS+mk7DPL9ThKD8e0LtGEdClB1nPlknM1nQobdzMoHBEYei/COsUcWUKojwRjAq5lEe9LFe3edVMSvT5dR4IuXMj1UFNV/QCmzcumsdMf9120TYe9SiND26i8fDSyrnKPAhy3jOpteoK8p1uraV+5IFINx/z+5wQ0h9PjUQA9s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
